### PR TITLE
Added everything to the creative inventory.

### PR DESCRIPTION
**Pull request by bigjango13**
Adds 87 items/blocks.
Only problem is that it can't add blocks with data.

### CODE REVIEW

**Comment by mobilegmYT** [comment]
@bigjango13 use gitea, this is a mirror so changes won't be in final build

**Comment by bigjango13** [comment]
I am locked out of gitea because I forgot my password. Is there a way for TBR to reset my account?

**Comment by mobilegmYT** [comment]
> I am locked out of gitea because I forgot my password. Is there a way for TBR to reset my account?

Make a new account, I can send you mine if you want.

**Comment by bigjango13** [comment]
I can't, I don't have an extra email account. Should I make one?

**Comment by mobilegmYT** [comment]
If you want, or I can also PR it for you.

**Comment by bigjango13** [comment]
I will make a new email.

**Pull request closed without merging**
